// 30-Day Job-Ready Roadmap — personalised day-by-day plan generated by GPT-5.2.
// Stores roadmap + completion progress in AsyncStorage so it survives app restarts.
// Each day shows focus icon, 3 tasks, daily tip, and a "Mark done" toggle.
import React, { useCallback, useEffect, useMemo, useState } from 'react';
import {
  View,
  StyleSheet,
  ScrollView,
  Pressable,
  ActivityIndicator,
  TextInput as RNTextInput,
  Platform,
  StatusBar,
} from 'react-native';
import { Text } from 'react-native-paper';
import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import { SafeAreaView, useSafeAreaInsets } from 'react-native-safe-area-context';
import AsyncStorage from '@react-native-async-storage/async-storage';
import * as Haptics from 'expo-haptics';
import { useNavigation } from '@react-navigation/native';
import type { NativeStackNavigationProp } from '@react-navigation/native-stack';

import { RootStackParamList } from '@/navigation/types';
import { aiService, QuotaExceededError } from '@/services/aiService';
import { useAuth } from '@/contexts/AuthContext';
import { JobRoadmap, RoadmapDay } from '@/types';
import { radius, spacing } from '@/config/theme';

type Nav = NativeStackNavigationProp<RootStackParamList>;

const STORAGE_KEY = 'speakmate.roadmap.v1';

const ROLE_PRESETS = [
  'Software Engineer (Fresher)',
  'Sales Executive',
  'Customer Support',
  'Data Analyst',
  'Business Analyst',
  'General / Any role',
];
const LEVELS: ('beginner' | 'intermediate' | 'advanced')[] = ['beginner', 'intermediate', 'advanced'];
const WEAK_OPTS = ['grammar', 'vocabulary', 'confidence', 'pronunciation', 'interview', 'tmay'];

const FOCUS_META: Record<string, { color: string; icon: keyof typeof import('@expo/vector-icons').Ionicons.glyphMap }> = {
  speaking:   { color: '#FF6B9D', icon: 'mic' },
  vocabulary: { color: '#22D3EE', icon: 'book' },
  tmay:       { color: '#A992FF', icon: 'person' },
  interview:  { color: '#7C5CFF', icon: 'briefcase' },
  resume:     { color: '#FACC15', icon: 'document-text' },
  grammar:    { color: '#34D399', icon: 'checkmark-done' },
  confidence: { color: '#FF7A6B', icon: 'flash' },
  listening:  { color: '#60A5FA', icon: 'headset' },
};

function focusMeta(focus: string) {
  return FOCUS_META[focus?.toLowerCase()] || FOCUS_META.speaking;
}

export default function RoadmapScreen() {
  const navigation = useNavigation<Nav>();
  const { user } = useAuth();
  const insets = useSafeAreaInsets();

  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [roadmap, setRoadmap] = useState<JobRoadmap | null>(null);
  const [error, setError] = useState<string | null>(null);

  // Setup form state
  const [roleTarget, setRoleTarget] = useState<string>(ROLE_PRESETS[0]);
  const [level, setLevel] = useState<'beginner' | 'intermediate' | 'advanced'>('beginner');
  const [weakAreas, setWeakAreas] = useState<string[]>([]);
  const [dailyMinutes, setDailyMinutes] = useState('15');

  // Load from storage on mount
  useEffect(() => {
    (async () => {
      try {
        const raw = await AsyncStorage.getItem(STORAGE_KEY);
        if (raw) {
          const parsed = JSON.parse(raw) as JobRoadmap;
          if (parsed?.days?.length) setRoadmap(parsed);
        }
      } catch {/* noop */}
      setLoading(false);
    })();
  }, []);

  const persist = useCallback(async (r: JobRoadmap) => {
    try { await AsyncStorage.setItem(STORAGE_KEY, JSON.stringify(r)); } catch {/* noop */}
  }, []);

  const toggleWeak = (w: string) => {
    setWeakAreas((prev) => (prev.includes(w) ? prev.filter((x) => x !== w) : [...prev, w]));
  };

  const generate = useCallback(async () => {
    setError(null); setGenerating(true);
    try {
      const r = await aiService.generateRoadmap({
        userName: user?.displayName || undefined,
        roleTarget,
        currentLevel: level,
        weakAreas,
        dailyMinutes: parseInt(dailyMinutes || '15', 10),
      });
      setRoadmap(r);
      await persist(r);
      Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success).catch(() => {});
    } catch (e) {
      if (e instanceof QuotaExceededError) {
        setError(`Daily free limit reached (${e.used}/${e.limit}). Upgrade to Premium for unlimited.`);
      } else {
        setError(e instanceof Error ? e.message : 'Failed to generate roadmap');
      }
    } finally {
      setGenerating(false);
    }
  }, [user, roleTarget, level, weakAreas, dailyMinutes, persist]);

  const toggleDay = useCallback((day: number) => {
    if (!roadmap) return;
    const set = new Set(roadmap.completedDays || []);
    if (set.has(day)) set.delete(day); else set.add(day);
    const updated: JobRoadmap = { ...roadmap, completedDays: Array.from(set).sort((a, b) => a - b) };
    setRoadmap(updated);
    persist(updated);
    Haptics.selectionAsync().catch(() => {});
  }, [roadmap, persist]);

  const resetRoadmap = useCallback(async () => {
    await AsyncStorage.removeItem(STORAGE_KEY);
    setRoadmap(null);
  }, []);

  const progress = useMemo(() => {
    if (!roadmap) return 0;
    return roadmap.completedDays.length / 30;
  }, [roadmap]);

  if (loading) {
    return (
      <View style={[styles.center, { backgroundColor: '#0A0418' }]}>
        <ActivityIndicator color="#A992FF" />
      </View>
    );
  }

  return (
    <View style={{ flex: 1, backgroundColor: '#0A0418' }}>
      <LinearGradient colors={['#1F0E3D', '#0A0418', '#150828']} style={StyleSheet.absoluteFillObject} />
      <SafeAreaView style={{ flex: 1 }} edges={['left', 'right']}>
        <ScrollView contentContainerStyle={{ paddingBottom: 140 }} showsVerticalScrollIndicator={false}>
          {/* Header */}
          <View style={[styles.header, { paddingTop: Math.max(insets.top, StatusBar.currentHeight ?? 0, 48) + 16 }]}>
            <Pressable onPress={() => navigation.goBack()} style={styles.iconBtn} testID="roadmap-back-btn">
              <Ionicons name="chevron-back" size={20} color="#F2EEFF" />
            </Pressable>
            <View style={{ flex: 1, marginLeft: spacing.md }}>
              <Text style={styles.title}>30-Day Job Ready Roadmap</Text>
              <Text style={styles.subtitle}>AI-personalised · daily 5-15 min plan</Text>
            </View>
            {roadmap ? (
              <Pressable onPress={resetRoadmap} style={styles.iconBtn} testID="roadmap-reset-btn">
                <Ionicons name="refresh" size={18} color="#F2EEFF" />
              </Pressable>
            ) : null}
          </View>

          {error ? (
            <View style={styles.errorBox}>
              <Ionicons name="warning" size={14} color="#FCA5A5" />
              <Text style={styles.errorText}>{error}</Text>
            </View>
          ) : null}

          {!roadmap ? (
            <>
              {/* SETUP FORM */}
              <Text style={styles.section}>Your target role</Text>
              <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.rolesRow}>
                {ROLE_PRESETS.map((r) => {
                  const active = r === roleTarget;
                  return (
                    <Pressable key={r} onPress={() => setRoleTarget(r)} style={[styles.pill, active && styles.pillActive]} testID={`roadmap-role-${r}`}>
                      <Text style={[styles.pillText, active && { color: '#0A0418' }]}>{r}</Text>
                    </Pressable>
                  );
                })}
              </ScrollView>

              <Text style={styles.section}>Current level</Text>
              <View style={styles.row}>
                {LEVELS.map((l) => {
                  const active = l === level;
                  return (
                    <Pressable key={l} onPress={() => setLevel(l)} style={[styles.pill, active && styles.pillActive]} testID={`roadmap-level-${l}`}>
                      <Text style={[styles.pillText, active && { color: '#0A0418' }]}>{l[0].toUpperCase() + l.slice(1)}</Text>
                    </Pressable>
                  );
                })}
              </View>

              <Text style={styles.section}>Weak areas (tap to toggle)</Text>
              <View style={styles.row}>
                {WEAK_OPTS.map((w) => {
                  const active = weakAreas.includes(w);
                  return (
                    <Pressable key={w} onPress={() => toggleWeak(w)} style={[styles.pill, active && styles.pillActive]} testID={`roadmap-weak-${w}`}>
                      <Text style={[styles.pillText, active && { color: '#0A0418' }]}>{w}</Text>
                    </Pressable>
                  );
                })}
              </View>

              <Text style={styles.section}>Daily commitment (minutes)</Text>
              <View style={[styles.row, { paddingHorizontal: spacing.lg }]}>
                <RNTextInput
                  value={dailyMinutes}
                  onChangeText={(v) => setDailyMinutes(v.replace(/[^0-9]/g, '').slice(0, 3))}
                  keyboardType="number-pad"
                  style={styles.minutesInput}
                  testID="roadmap-minutes-input"
                />
                <Text style={{ color: '#A992FF', fontWeight: '700', alignSelf: 'center' }}>min/day</Text>
              </View>

              <Pressable
                onPress={generate}
                disabled={generating}
                style={[styles.generateBtn, generating && { opacity: 0.6 }]}
                testID="roadmap-generate-btn"
              >
                <LinearGradient colors={['#7C5CFF', '#A992FF']} start={{ x: 0, y: 0 }} end={{ x: 1, y: 1 }} style={styles.generateInner}>
                  {generating ? (
                    <ActivityIndicator color="#FFFFFF" />
                  ) : (
                    <>
                      <Ionicons name="sparkles" size={18} color="#FFFFFF" />
                      <Text style={styles.generateText}>Generate my 30-day plan</Text>
                    </>
                  )}
                </LinearGradient>
              </Pressable>
              <Text style={styles.note}>Takes ~15-30s · Powered by GPT-5.2</Text>
            </>
          ) : (
            <>
              {/* ROADMAP VIEW */}
              <LinearGradient
                colors={['rgba(124,92,255,0.2)', 'rgba(34,211,238,0.1)']}
                style={styles.summaryCard}
              >
                <Text style={styles.goalTitle}>{roadmap.goal_title}</Text>
                <Text style={styles.summary}>{roadmap.summary}</Text>
                <View style={styles.progRow}>
                  <Text style={styles.progLabel}>
                    {roadmap.completedDays.length} / 30 days · {Math.round(progress * 100)}% complete
                  </Text>
                  <View style={styles.progTrack}>
                    <LinearGradient
                      colors={['#34D399', '#22D3EE']}
                      start={{ x: 0, y: 0 }} end={{ x: 1, y: 0 }}
                      style={[styles.progFill, { width: `${progress * 100}%` }]}
                    />
                  </View>
                </View>
              </LinearGradient>

              <Text style={styles.section}>Your 30-day plan</Text>
              {roadmap.days.map((d) => (
                <DayCard
                  key={d.day}
                  day={d}
                  done={roadmap.completedDays.includes(d.day)}
                  onToggle={() => toggleDay(d.day)}
                />
              ))}
            </>
          )}
        </ScrollView>
      </SafeAreaView>
    </View>
  );
}

function DayCard({ day, done, onToggle }: { day: RoadmapDay; done: boolean; onToggle: () => void }) {
  const meta = focusMeta(day.focus);
  return (
    <View style={[styles.dayCard, done && styles.dayCardDone]}>
      <View style={styles.dayHead}>
        <View style={[styles.focusIcon, { backgroundColor: `${meta.color}25`, borderColor: `${meta.color}55` }]}>
          <Ionicons name={meta.icon} size={18} color={meta.color} />
        </View>
        <View style={{ flex: 1, marginLeft: spacing.md }}>
          <Text style={styles.dayLabel}>DAY {day.day} · <Text style={{ color: meta.color }}>{day.focus.toUpperCase()}</Text></Text>
          <Text style={styles.dayTitle}>{day.title}</Text>
        </View>
        <Pressable onPress={onToggle} style={[styles.checkBox, done && { backgroundColor: '#34D399', borderColor: '#34D399' }]} testID={`roadmap-day-${day.day}-toggle`}>
          {done ? <Ionicons name="checkmark" size={16} color="#0A0418" /> : null}
        </Pressable>
      </View>
      <View style={{ marginTop: spacing.sm, gap: 6 }}>
        {day.tasks.map((t, i) => (
          <View key={i} style={{ flexDirection: 'row' }}>
            <Text style={{ color: '#A992FF', marginRight: 6, fontWeight: '700' }}>{i + 1}.</Text>
            <Text style={styles.taskText}>{t}</Text>
          </View>
        ))}
      </View>
      {!!day.tip && (
        <View style={styles.tipRow}>
          <Ionicons name="bulb" size={12} color="#FACC15" />
          <Text style={styles.tipText}>{day.tip}</Text>
        </View>
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  center: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  header: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: spacing.lg, paddingTop: spacing.md, paddingBottom: spacing.sm },
  iconBtn: { width: 38, height: 38, borderRadius: 19, backgroundColor: 'rgba(255,255,255,0.06)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)', alignItems: 'center', justifyContent: 'center' },
  title: { color: '#F2EEFF', fontSize: 20, fontWeight: '800' },
  subtitle: { color: '#A992FF', fontSize: 12, fontWeight: '700', marginTop: 2 },

  errorBox: { flexDirection: 'row', alignItems: 'center', gap: 6, marginHorizontal: spacing.lg, marginTop: spacing.sm, padding: spacing.sm, borderRadius: radius.md, backgroundColor: 'rgba(239,68,68,0.1)', borderWidth: 1, borderColor: 'rgba(239,68,68,0.3)' },
  errorText: { color: '#FCA5A5', fontSize: 12, flex: 1 },

  section: { color: '#F2EEFF', fontSize: 14, fontWeight: '800', marginTop: spacing.lg, marginBottom: spacing.sm, paddingHorizontal: spacing.lg },
  rolesRow: { paddingHorizontal: spacing.lg, gap: spacing.sm, paddingVertical: 4 },
  row: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, paddingHorizontal: spacing.lg },
  pill: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: radius.pill, borderWidth: 1, borderColor: 'rgba(255,255,255,0.15)', backgroundColor: 'rgba(255,255,255,0.04)' },
  pillActive: { backgroundColor: '#A992FF', borderColor: '#A992FF' },
  pillText: { color: '#F2EEFF', fontSize: 12, fontWeight: '700' },
  minutesInput: { flex: 1, color: '#F2EEFF', fontSize: 18, fontWeight: '800', backgroundColor: 'rgba(255,255,255,0.06)', borderRadius: radius.md, paddingHorizontal: spacing.md, paddingVertical: spacing.sm, borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)' },

  generateBtn: { marginHorizontal: spacing.lg, marginTop: spacing.xl, borderRadius: radius.pill, overflow: 'hidden' },
  generateInner: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, paddingVertical: 16 },
  generateText: { color: '#FFFFFF', fontWeight: '800', fontSize: 14 },
  note: { color: 'rgba(242,238,255,0.5)', fontSize: 11, textAlign: 'center', marginTop: spacing.sm, fontStyle: 'italic' },

  summaryCard: { marginHorizontal: spacing.lg, marginTop: spacing.lg, padding: spacing.lg, borderRadius: radius.xl, borderWidth: 1, borderColor: 'rgba(124,92,255,0.3)' },
  goalTitle: { color: '#F2EEFF', fontSize: 18, fontWeight: '800' },
  summary: { color: 'rgba(242,238,255,0.7)', fontSize: 13, marginTop: 6, lineHeight: 19 },
  progRow: { marginTop: spacing.md },
  progLabel: { color: '#A992FF', fontSize: 11, fontWeight: '800', marginBottom: 6 },
  progTrack: { height: 8, backgroundColor: 'rgba(255,255,255,0.06)', borderRadius: 4, overflow: 'hidden' },
  progFill: { height: '100%' },

  dayCard: { marginHorizontal: spacing.lg, marginBottom: spacing.md, padding: spacing.md, borderRadius: radius.lg, borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)', backgroundColor: 'rgba(255,255,255,0.04)' },
  dayCardDone: { backgroundColor: 'rgba(52,211,153,0.08)', borderColor: 'rgba(52,211,153,0.3)' },
  dayHead: { flexDirection: 'row', alignItems: 'center' },
  focusIcon: { width: 38, height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center', borderWidth: 1 },
  dayLabel: { color: 'rgba(242,238,255,0.6)', fontSize: 9, fontWeight: '800', letterSpacing: 0.5 },
  dayTitle: { color: '#F2EEFF', fontSize: 14, fontWeight: '800', marginTop: 2 },
  checkBox: { width: 26, height: 26, borderRadius: 13, borderWidth: 1.5, borderColor: 'rgba(255,255,255,0.25)', alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,0.04)' },
  taskText: { color: '#F2EEFF', fontSize: 12, flex: 1, lineHeight: 17 },
  tipRow: { flexDirection: 'row', alignItems: 'center', gap: 5, marginTop: spacing.sm, paddingTop: spacing.sm, borderTopWidth: 1, borderTopColor: 'rgba(255,255,255,0.06)' },
  tipText: { color: '#FACC15', fontSize: 11, flex: 1, fontStyle: 'italic', lineHeight: 15 },
});
