# =============================================================================
# SpeakMate AI - One-Shot UI Overlap Fix + AAB Build (Cloud Sync Edition v2)
# =============================================================================
# Run from D:\sm\SpeakMateAI:
#     powershell -ExecutionPolicy Bypass -File .\fix-overlap-and-build.ps1
# =============================================================================

$ErrorActionPreference = "Continue"
$startTime = Get-Date

# Cloud URLs
$CloudBase = "https://gift-hub-sync.preview.emergentagent.com/api/fix-files"
$Files = @(
    @{ Url = "$CloudBase/useScreenInsets.ts";         Dest = "src\hooks\useScreenInsets.ts" }
    @{ Url = "$CloudBase/ScreenContainer.tsx";        Dest = "src\components\common\ScreenContainer.tsx" }
    @{ Url = "$CloudBase/SpeakingPracticeScreen.tsx"; Dest = "src\screens\speaking\SpeakingPracticeScreen.tsx" }
    @{ Url = "$CloudBase/InterviewCoachScreen.tsx";   Dest = "src\screens\interview\InterviewCoachScreen.tsx" }
    @{ Url = "$CloudBase/PremiumScreen.tsx";          Dest = "src\screens\premium\PremiumScreen.tsx" }
)

function Write-Step { param([string]$Msg) Write-Host "" ; Write-Host "==> $Msg" -ForegroundColor Cyan }
function Write-Ok   { param([string]$Msg) Write-Host "    [OK]   $Msg" -ForegroundColor Green }
function Write-Warn { param([string]$Msg) Write-Host "    [WARN] $Msg" -ForegroundColor Yellow }
function Write-Err  { param([string]$Msg) Write-Host "    [ERR]  $Msg" -ForegroundColor Red }

# STEP 0 - Preflight
Write-Step "Preflight checks"
if (-not (Test-Path "package.json")) {
    Write-Err "Not in SpeakMateAI folder. cd D:\sm\SpeakMateAI first."
    exit 1
}
Write-Ok "In folder: $(Get-Location)"
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

# STEP 1 - Download latest fix files from cloud
Write-Step "Downloading latest UI-fix files from cloud"
$downloaded = 0
foreach ($f in $Files) {
    $destDir = Split-Path -Parent $f.Dest
    if ($destDir -and -not (Test-Path $destDir)) {
        New-Item -ItemType Directory -Force -Path $destDir | Out-Null
    }
    try {
        Invoke-WebRequest -Uri $f.Url -OutFile $f.Dest -UseBasicParsing -TimeoutSec 30
        $size = [math]::Round((Get-Item $f.Dest).Length / 1KB, 1)
        Write-Ok "$($f.Dest)  ($size KB)"
        $downloaded++
    } catch {
        Write-Err "Failed: $($f.Url)"
        Write-Err $_.Exception.Message
        Write-Warn "Continuing with existing local copy of $($f.Dest)"
    }
}
Write-Ok "$downloaded / $($Files.Count) files refreshed from cloud"

# STEP 2 - Ensure node_modules is installed (expo CLI needs it)
Write-Step "Verifying node_modules is installed"
if (-not (Test-Path "node_modules\expo\bin\cli")) {
    Write-Warn "node_modules\expo missing - running yarn install (this may take a few min)"
    & yarn install
    if ($LASTEXITCODE -ne 0) {
        Write-Err "yarn install failed. Try: yarn install --force"
        exit 1
    }
}
Write-Ok "node_modules ready"

# STEP 3 - Aggressively kill stale processes (Android Studio, Java, Gradle, Kotlin)
Write-Step "Killing stale Android Studio / Java / Gradle / Kotlin processes"
if (Test-Path "android\gradlew.bat") {
    Push-Location android
    & .\gradlew.bat --stop 2>$null | Out-Null
    Pop-Location
}
$procNames = @("java", "javaw", "kotlin-compiler-daemon", "kotlin-daemon", "studio64", "studio", "OpenJDK Platform binary", "GradleDaemon")
foreach ($p in $procNames) {
    Get-Process -Name $p -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue
}
Start-Sleep -Seconds 3
Write-Ok "Processes terminated (waited 3s for handles to release)"

# STEP 4 - Robust android folder backup (with retries + fallback to direct delete)
Write-Step "Backing up old android folder"
if (Test-Path "android") {
    $backupName = "android-backup-$(Get-Date -Format 'yyyyMMdd-HHmmss')"
    $renamed = $false
    for ($i = 1; $i -le 5; $i++) {
        try {
            Rename-Item "android" $backupName -Force -ErrorAction Stop
            $renamed = $true
            Write-Ok "Backed up android -> $backupName"
            break
        } catch {
            Write-Warn "Rename attempt $i/5 failed - waiting 5s then retrying..."
            Start-Sleep -Seconds 5
            # Try one more aggressive process kill each attempt
            Get-Process -Name "java", "javaw" -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue
        }
    }
    if (-not $renamed) {
        Write-Warn "Could not rename android folder (likely locked by Android Studio)."
        Write-Warn "Trying direct deletion instead (folder will be regenerated by prebuild anyway)..."
        try {
            Remove-Item "android" -Recurse -Force -ErrorAction Stop
            Write-Ok "Old android folder deleted"
        } catch {
            Write-Err "Could not delete android folder either."
            Write-Err "ACTION REQUIRED: Close Android Studio completely, then re-run this script."
            exit 1
        }
    }
}

# STEP 5 - expo prebuild --clean (use direct node call - more reliable on Windows)
Write-Step "Running expo prebuild --platform android --clean"
$expoCli = "node_modules\expo\bin\cli"
$prebuildOk = $false
if (Test-Path $expoCli) {
    & node $expoCli prebuild --platform android --clean --no-install
    if ($LASTEXITCODE -eq 0) { $prebuildOk = $true }
}
if (-not $prebuildOk) {
    Write-Warn "Direct node call failed - falling back to npx"
    & npx expo prebuild --platform android --clean --no-install
    if ($LASTEXITCODE -ne 0) {
        Write-Err "expo prebuild failed via both methods."
        Write-Err "ACTION REQUIRED: Run 'yarn install --force' manually then re-run this script."
        exit 1
    }
}
Write-Ok "Fresh android folder generated"

# STEP 6 - Patch gradle.properties (memory + Kotlin in-process)
Write-Step "Patching android/gradle.properties (4 GB heap, in-process Kotlin)"
$gradleProps = "android\gradle.properties"
$gradleAppend = "`r`n# === SpeakMate AI build properties (auto-added) ===`r`n"
$gradleAppend += "org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8`r`n"
$gradleAppend += "org.gradle.daemon=false`r`n"
$gradleAppend += "org.gradle.parallel=false`r`n"
$gradleAppend += "org.gradle.workers.max=1`r`n"
$gradleAppend += "kotlin.daemon.jvm.options=-Xmx2048m`r`n"
$gradleAppend += "kotlin.compiler.execution.strategy=in-process`r`n"
$gradleAppend += "kotlin.incremental=false`r`n"
Add-Content $gradleProps $gradleAppend
Write-Ok "gradle.properties patched"

# STEP 7 - Patch app/build.gradle (lintOptions + release signing)
Write-Step "Patching app/build.gradle (lintOptions + release signing)"
$appGradle = "android\app\build.gradle"
$content = Get-Content $appGradle -Raw

# 7a. Add lintOptions block if missing (Expo prebuild often already has `lint { ... }`)
if ($content -notmatch "lintOptions" -and $content -notmatch "lint\s*\{") {
    $content = $content -replace '(android\s*\{[^\n]*\n)', "`$1    lintOptions { abortOnError false; checkReleaseBuilds false }`r`n"
    Write-Ok "lintOptions block added"
}

# 7b. Wire release keystore (only if .jks present)
if (Test-Path "speakmateai-release.jks") {
    if ($content -notmatch "keystorePropertiesFile") {

        # ---- STEP A: Prepend keystore loader at the VERY TOP of build.gradle ----
        # This puts the Properties variable in script-global scope so the release {}
        # block inside signingConfigs can read it.
        $loader = "def keystorePropertiesFile = rootProject.file('keystore.properties')`r`n"
        $loader += "def keystoreProperties = new Properties()`r`n"
        $loader += "if (keystorePropertiesFile.exists()) {`r`n"
        $loader += "    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))`r`n"
        $loader += "}`r`n`r`n"
        $content = $loader + $content

        # ---- STEP B: Insert release {} block inside signingConfigs { debug { ... } } ----
        # Match the entire debug { ... } block (it ends with `keyPassword 'android'` then `}`)
        # and inject the release block immediately AFTER it (still inside signingConfigs).
        $releaseSigning = @'

        release {
            if (keystorePropertiesFile.exists()) {
                storeFile file(keystoreProperties['storeFile'])
                storePassword keystoreProperties['storePassword']
                keyAlias keystoreProperties['keyAlias']
                keyPassword keystoreProperties['keyPassword']
            }
        }
'@
        # The regex matches the debug block's closing brace. We append the release block right after it.
        # (?ms) = multiline + dotall. \r?\n handles both CRLF/LF.
        $debugBlockPattern = "(?ms)(signingConfigs\s*\{\s*debug\s*\{[^}]+keyPassword\s+'android'\s*\r?\n\s*\})"
        if ($content -match $debugBlockPattern) {
            $content = $content -replace $debugBlockPattern, "`$1$releaseSigning"
            Write-Ok "Release signing block inserted into signingConfigs"
        } else {
            Write-Warn "Could not find debug signing block - release block NOT inserted (manual fix needed)"
        }

        # ---- STEP C: Change release buildType to use signingConfigs.release ----
        # Match ONLY the signingConfig line inside the release {} buildType (not debug)
        $content = $content -replace "(release\s*\{[^}]*signingConfig\s+signingConfigs\.)debug", '$1release'
        Write-Ok "Release buildType now uses signingConfigs.release"

    } else {
        Write-Ok "Release signing already wired"
    }
} else {
    Write-Warn "speakmateai-release.jks not found - AAB will be debug-signed (NOT uploadable)"
}
Set-Content $appGradle -Value $content -NoNewline

# STEP 8 - keystore.properties (prompt if missing)
$keystoreProps = "android\keystore.properties"
if ((Test-Path "speakmateai-release.jks") -and -not (Test-Path $keystoreProps)) {
    Write-Step "Creating android/keystore.properties"
    $storePass = Read-Host "  Keystore password" -AsSecureString
    $keyAlias  = Read-Host "  Key alias (e.g., speakmate-release)"
    $sp = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto(
        [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($storePass))
    $ksContent = "storeFile=../../speakmateai-release.jks`r`n"
    $ksContent += "storePassword=$sp`r`n"
    $ksContent += "keyAlias=$keyAlias`r`n"
    $ksContent += "keyPassword=$sp`r`n"
    Set-Content $keystoreProps -Value $ksContent
    Write-Ok "keystore.properties created"
}

# STEP 9 - Build the Release AAB
Write-Step "Building Release AAB for Play Store (~10-20 min)"
Push-Location android
& .\gradlew bundleRelease --no-daemon --max-workers=1 -x lintVitalAnalyzeRelease
$buildExit = $LASTEXITCODE
Pop-Location

if ($buildExit -ne 0) {
    Write-Err "AAB build failed (exit $buildExit)."
    Write-Host "    - Close Android Studio + all gradle daemons" -ForegroundColor White
    Write-Host "    - Re-run this script" -ForegroundColor White
    Write-Host "    - If still failing: delete %USERPROFILE%\.gradle\caches and retry" -ForegroundColor White
    exit $buildExit
}

$aabPath = "android\app\build\outputs\bundle\release\app-release.aab"
if (Test-Path $aabPath) {
    $aabSize = [math]::Round((Get-Item $aabPath).Length / 1MB, 2)
    Write-Ok "AAB built: $aabPath ($aabSize MB)"
} else {
    Write-Err "AAB not found at $aabPath"
    exit 1
}

# DONE
$duration = (Get-Date) - $startTime
Write-Host ""
Write-Host "================================================================" -ForegroundColor Green
Write-Host "  UI FIX + AAB BUILD COMPLETE" -ForegroundColor Green
Write-Host "  Total time: $([math]::Round($duration.TotalMinutes, 1)) minutes" -ForegroundColor Green
Write-Host "================================================================" -ForegroundColor Green
Write-Host ""
Write-Host "  AAB ready for Play Store upload:" -ForegroundColor Cyan
Write-Host "  $((Get-Item $aabPath).FullName)" -ForegroundColor White
Write-Host ""

Start-Process "explorer.exe" -ArgumentList (Split-Path -Parent (Resolve-Path $aabPath))
